# basic workflow to generate a plot of the precip

name: rainfall_plots
on:
  workflow_dispatch:
    inputs:
      airport:
        description: ICAO Airport Code

      start_date:
        description: 'Date to start (y/m/d) - e.g. 2000-01-01'
        default: '2000-01-01'

      end_date:
        description: 'Date to end (y/m/d) - e.g. 2020-12-01'
        default: '2022-09-13'

jobs:
  plot:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate Rainfall plot
        run: |
          mkdir output
          python main.py -t0 ${{github.event.inputs.start_date}} -t1 ${{github.event.inputs.end_date}} --airport ${{github.event.inputs.airport}}

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
         name: ${{github.event.inputs.airport}}-precip
         path: output
